'use client';

import React, { useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { 
  Globe, 
  Sparkles, 
  Code, 
  Eye, 
  Copy, 
  Check, 
  Play, 
  FileCode,
  Laptop
} from 'lucide-react';

export default function WebsiteBuilderPage() {
  const { token } = useAuth();
  
  const [docType, setDocType] = useState('landing');
  const [customPrompt, setCustomPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [generatedHtml, setGeneratedHtml] = useState<string>(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BizBrain HQ - Premium Landing Page</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-white font-sans min-h-screen flex flex-col justify-between">
  <header class="p-6 max-w-6xl mx-auto w-full flex justify-between items-center">
    <div class="text-xl font-extrabold text-blue-500 tracking-wider">BIZBRAIN HQ</div>
    <nav class="flex gap-6 text-sm text-slate-400">
      <a href="#" class="hover:text-white transition-colors">Features</a>
      <a href="#" class="hover:text-white transition-colors">Pricing</a>
      <a href="#" class="hover:text-white transition-colors">FAQ</a>
    </nav>
  </header>

  <main class="max-w-4xl mx-auto px-6 py-20 text-center space-y-8 flex-1 flex flex-col justify-center">
    <span class="px-3 py-1 bg-blue-500/10 text-blue-400 rounded-full text-xs font-bold uppercase tracking-widest inline-block mx-auto">
      AI Generated Landing Page
    </span>
    <h1 class="text-5xl font-extrabold leading-tight bg-gradient-to-r from-blue-500 via-cyan-400 to-emerald-400 bg-clip-text text-transparent">
      Unlock Hyper-Growth for Your SME Business
    </h1>
    <p class="text-slate-400 max-w-lg mx-auto text-sm leading-relaxed">
      BizBrain AI manages your orders, inventory metrics, tax filing reports, and customer pipelines in one secure hub.
    </p>
    <div>
      <button class="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-bold shadow-lg shadow-blue-500/20 transition-all">
        Start Free Trial
      </button>
    </div>
  </main>

  <footer class="p-6 text-center text-xs text-slate-650 border-t border-slate-900">
    &copy; 2026 BizBrain HQ. Generated by BizBrain AI Copilot.
  </footer>
</body>
</html>
  `);

  const [activeView, setActiveView] = useState<'preview' | 'code'>('preview');
  const [copied, setCopied] = useState(false);

  const handleGenerateWebsite = async () => {
    setLoading(true);
    try {
      const finalPrompt = customPrompt 
        ? `Create a modern fully styled HTML page for a ${docType} page. Custom requests: ${customPrompt}`
        : `Create a modern fully styled HTML page for a ${docType} page using Tailwind CSS classes. Make it look beautiful and corporate.`;

      const res = await fetch('http://localhost:5000/api/ai/generator', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          docType: 'html',
          prompt: finalPrompt
        })
      });

      if (res.ok) {
        const data = await res.json();
        // Parse code blocks if AI wrapped it in ```html ... ```
        let cleanHtml = data.content;
        if (cleanHtml.includes('```html')) {
          cleanHtml = cleanHtml.split('```html')[1].split('```')[0];
        } else if (cleanHtml.includes('```')) {
          cleanHtml = cleanHtml.split('```')[1].split('```')[0];
        }
        setGeneratedHtml(cleanHtml);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generatedHtml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-[calc(100vh-130px)] flex flex-col lg:flex-row gap-6 select-none overflow-hidden">
      
      {/* Left panel: Config controls */}
      <div className="w-full lg:w-80 shrink-0 h-full flex flex-col bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 justify-between">
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <span className="p-1.5 bg-blue-500/10 text-blue-500 rounded-lg"><Globe className="w-4 h-4" /></span>
            <h2 className="font-bold text-sm tracking-tight text-slate-900 dark:text-white">AI Landing Page Generator</h2>
          </div>
          <p className="text-xs text-slate-500 leading-relaxed">
            Specify the section page layout you wish to compile and type instructions to theme the CSS.
          </p>

          <div className="space-y-3 pt-2">
            <div>
              <label className="block text-[10px] uppercase font-bold text-slate-400 mb-1">Target Page Type</label>
              <select
                value={docType}
                onChange={(e) => setDocType(e.target.value)}
                className="w-full px-3 py-2 bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg text-xs outline-none focus:ring-2 focus:ring-blue-500 text-slate-800 dark:text-slate-200"
              >
                <option value="landing">Main Landing Page</option>
                <option value="about">About Us Page</option>
                <option value="contact">Contact Desk Form</option>
                <option value="catalog">Product Catalog</option>
                <option value="faq">FAQ Accordion</option>
                <option value="blog">Article Blog Roll</option>
              </select>
            </div>

            <div>
              <label className="block text-[10px] uppercase font-bold text-slate-400 mb-1">Custom Styling Prompt</label>
              <textarea
                rows={4}
                placeholder="e.g. Dark mode cyber theme for robotic components shipping, include 3 service features cards..."
                value={customPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                className="w-full px-3 py-2 bg-slate-100 dark:bg-slate-950 border-none rounded-lg text-xs outline-none focus:ring-2 focus:ring-blue-500 text-slate-800 dark:text-slate-200"
              />
            </div>
          </div>
        </div>

        <button
          onClick={handleGenerateWebsite}
          disabled={loading}
          className="w-full py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 shadow shadow-blue-600/10 disabled:opacity-40 transition-colors mt-4"
        >
          {loading ? (
            <>
              <Sparkles className="w-3.5 h-3.5 animate-spin" /> Compiling layout...
            </>
          ) : (
            <>
              <Play className="w-3.5 h-3.5" /> Compile Website
            </>
          )}
        </button>
      </div>

      {/* Right panel: Preview frame */}
      <div className="flex-1 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl overflow-hidden flex flex-col h-full">
        {/* Toggle controls */}
        <div className="px-4 py-3 bg-slate-50 dark:bg-slate-950/20 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center">
          <div className="flex gap-2">
            <button
              onClick={() => setActiveView('preview')}
              className={`px-3 py-1 text-xs font-semibold rounded-lg flex items-center gap-1.5 transition-colors ${
                activeView === 'preview' 
                  ? 'bg-slate-250 dark:bg-slate-800 text-slate-900 dark:text-white' 
                  : 'text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800/40'
              }`}
            >
              <Eye className="w-3.5 h-3.5" /> View Site
            </button>
            <button
              onClick={() => setActiveView('code')}
              className={`px-3 py-1 text-xs font-semibold rounded-lg flex items-center gap-1.5 transition-colors ${
                activeView === 'code' 
                  ? 'bg-slate-250 dark:bg-slate-800 text-slate-900 dark:text-white' 
                  : 'text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800/40'
              }`}
            >
              <Code className="w-3.5 h-3.5" /> View HTML Source
            </button>
          </div>

          {activeView === 'code' && (
            <button
              onClick={handleCopyCode}
              className="flex items-center gap-1.5 text-xs text-blue-500 font-bold hover:underline"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy Code'}</span>
            </button>
          )}
        </div>

        {/* View content panel */}
        <div className="flex-1 bg-slate-100 dark:bg-slate-950/50 p-4 h-[calc(100%-50px)] overflow-hidden">
          {activeView === 'preview' ? (
            <div className="w-full h-full bg-white rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden flex flex-col shadow-inner">
              <div className="h-6 bg-slate-50 border-b border-slate-150 flex items-center px-4 gap-1.5 shrink-0">
                <Laptop className="w-3 h-3 text-slate-400" />
                <span className="text-[9px] font-mono text-slate-400">sandbox://generated-sme-site/index.html</span>
              </div>
              <iframe
                title="Generated Preview"
                srcDoc={generatedHtml}
                className="w-full flex-1 border-none bg-white"
                sandbox="allow-scripts"
              />
            </div>
          ) : (
            <div className="w-full h-full bg-slate-900 text-slate-300 font-mono text-xs rounded-xl p-4 overflow-y-auto border border-slate-800 shadow-inner">
              <pre className="whitespace-pre-wrap">{generatedHtml}</pre>
            </div>
          )}
        </div>
      </div>

    </div>
  );
}
